import { useState, useRef } from "react";
import API_BASE from "../config";

export default function ExportButton({ data }) {
  const [speaking, setSpeaking] = useState(false);
  const [copied, setCopied] = useState(false);
  const [loadingAudio, setLoadingAudio] = useState(false);
  const audioRef = useRef(null);

  const buildMarkdown = () => [
    `# ${data.title}`,
    `**Authors:** ${data.authors}`,
    `**Pages:** ${data.total_pages} | **Reading Level:** ${data.reading_level}`,
    `\n---\n`,
    `## Summary`,
    data.summary,
    `\n## ELI5 Summary`,
    data.eli5_summary,
    `\n## Core Claims`,
    ...(data.claims || []).map(
      (c) => `- **[${c.verified ? "✅ Verified" : "⚠️ Flagged"}] Page ${c.page}** (${Math.round(c.confidence * 100)}%): ${c.text}`
    ),
    `\n## Limitations`,
    ...(data.limitations || []).map((l) => `- ${l}`),
    `\n## Flashcards`,
    ...(data.flashcards || []).map((f) => `**Q:** ${f.front}\n**A:** ${f.back}\n`),
    `\n## Key Terms`,
    ...(data.key_terms || []).map((t) => `- **${t.term}**: ${t.definition}`),
    `\n---`,
    `*Generated by ScholarSwarm*`,
  ].join("\n");

  const handleDownload = () => {
    const blob = new Blob([buildMarkdown()], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.title?.slice(0, 40).replace(/[^a-z0-9]/gi, "-")}-brief.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildMarkdown());
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for browsers that block clipboard
      const textarea = document.createElement("textarea");
      textarea.value = buildMarkdown();
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const handleAudio = async () => {
    // Stop if already playing
    if (speaking) {
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current = null;
      }
      setSpeaking(false);
      return;
    }

    setLoadingAudio(true);
    const text = `Paper: ${data.title}. Summary: ${data.summary}`;

    try {
      const res = await fetch(`${API_BASE}/tts`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });

      if (!res.ok) throw new Error("TTS failed");

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      audioRef.current = audio;

      audio.onended = () => {
        setSpeaking(false);
        URL.revokeObjectURL(url);
      };
      audio.onerror = () => {
        setSpeaking(false);
        URL.revokeObjectURL(url);
      };

      await audio.play();
      setSpeaking(true);
    } catch {
      // Fallback to browser TTS
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 0.88;
      utterance.onend = () => setSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setSpeaking(true);
    } finally {
      setLoadingAudio(false);
    }
  };

  return (
    <div className="flex flex-wrap gap-2">
      <button
        onClick={handleDownload}
        className="flex items-center gap-2 text-sm px-4 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 rounded-xl text-gray-300 transition-all"
      >
        ⬇️ Markdown
      </button>

      <button
        onClick={handleCopy}
        className={`flex items-center gap-2 text-sm px-4 py-2 border rounded-xl transition-all
          ${copied
            ? "bg-green-500/10 border-green-500/40 text-green-400"
            : "bg-gray-800 hover:bg-gray-700 border-gray-700 text-gray-300"}`}
      >
        {copied ? "✅ Copied!" : "📋 Copy to Notion"}
      </button>

      <button
        onClick={handleAudio}
        disabled={loadingAudio}
        className={`flex items-center gap-2 text-sm px-4 py-2 border rounded-xl transition-all
          ${speaking
            ? "bg-violet-500/10 border-violet-500/40 text-violet-300"
            : loadingAudio
            ? "bg-gray-800 border-gray-700 text-gray-500 cursor-wait"
            : "bg-gray-800 hover:bg-gray-700 border-gray-700 text-gray-300"}`}
      >
        {loadingAudio
          ? <><span className="w-3 h-3 border-2 border-gray-500 border-t-transparent rounded-full animate-spin inline-block" /> Generating...</>
          : speaking ? "⏹️ Stop"
          : "🔊 Listen"}
      </button>
    </div>
  );
}
